[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pycorex"                # PyPIに登録されるパッケージ名
version = "1.0.1"
description = "A lightweight Python core package for unified AI API access, designed for flexibility and scalability."
readme = "README.md"            # 説明文としてREADMEを利用
license = {file = "LICENSE"}    # ライセンスファイル
authors = [
    { name="kaioman", email="kajin0318@gmail.com" }
]
dependencies = [
    "grpc-google-iam-v1>=0.13.0,<1.0.0",
    "google-api-core>=2.15.0,<3.0.0",
    "google-cloud-aiplatform>=1.38.0,<2.0.0",
    "libcore-hng>=2.0.30",
    "tiktoken>=0.5.0",
    "pillow>=10.0.0",
    "psutil>=5.9.0",
    "filetype>=1.2.0"
]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[project.urls]
Homepage = "https://github.com/kaioman/pycorex"
Repository = "https://github.com/kaioman/pycorex"
Issues = "https://github.com/kaioman/pycorex/issues"