[DEFAULT]

;LogFileName
LOGFILE_NAME = pycorex.log

;LogFileSuffix
;0=SuffixNone
;1=yyyyMMddhhmmss
;2=yyyyMMddhhmm
;3=yyyyMMdd
;4=yyMMdd
;5=MMdd
LOGFILE_NAME_SUFFIX = 3

;LogFolderName
LOGFOLDER_NAME = log

;LogFormat
LOGFORMAT = %%(levelname)s : %%(asctime)s : %%(message)s

;LogLevel
;10=DEBUG
;20=INFO
;30=WARNING
;40=ERROR
;50=CRITICAL
LOGLEVEL = 10
